backend:
  name: github
  repo: zilindeng/ephemeral-objects

media_folder: static/assets
public_folder: /assets

# publish_mode: editorial_workflow

collections:
  - name: blog
    label: Blog
    folder: src/content/blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: title, label: Title }
      - { name: date, label: Date, widget: date, format: MM—DD—YYYY }
      - { name: grid, label: Grid, }
      - { name: thumbnail, label: Thumbnail, widget: image }
      - { name: description, label: Description, widget: text }
